-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 15:08:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BancoReserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BancoReserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoReserva` DEFAULT CHARACTER SET utf8 ;
USE `BancoReserva` ;

-- -----------------------------------------------------
-- Table `BancoReserva`.`tb_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoReserva`.`tb_rooms` (
  `id_quartos` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` VARCHAR(4) NOT NULL,
  `walk` VARCHAR(5) NOT NULL,
  `description` VARCHAR(45) NULL,
  `characteristics` VARCHAR(45) NULL,
  `price_day` DECIMAL(7,2) NOT NULL,
  `state` VARCHAR(15) NOT NULL,
  `room_type` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_quartos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoReserva`.`tb_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoReserva`.`tb_person` (
  `id_person` INT NOT NULL AUTO_INCREMENT,
  `person_name` VARCHAR(45) NOT NULL,
  `father_name` VARCHAR(45) NOT NULL,
  `mother_name` VARCHAR(45) NOT NULL,
  `document_type` VARCHAR(45) NOT NULL,
  `num_document` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_person`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
