/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author ester
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setExtendedState(FrmMenu.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reservas para Hotéis - Pousada de Juventude");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menu_sistema = new javax.swing.JMenu();
        menu_arquivo = new javax.swing.JMenu();
        s_menu_quartos = new javax.swing.JMenuItem();
        s_menu_produtos = new javax.swing.JMenuItem();
        menu_reserva = new javax.swing.JMenu();
        s_menu_reservas = new javax.swing.JMenuItem();
        s_menu_clientes = new javax.swing.JMenuItem();
        s_menu_pagamentos = new javax.swing.JMenuItem();
        menu_consulta = new javax.swing.JMenu();
        menu_config = new javax.swing.JMenu();
        s_menu_usuario = new javax.swing.JMenuItem();
        menu_ferramenta = new javax.swing.JMenu();
        menu_ajuda = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(255, 255, 255));

        menu_sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/Inicio.png"))); // NOI18N
        menu_sistema.setMnemonic('f');
        menu_sistema.setText("System");
        menu_sistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_sistema);

        menu_arquivo.setMnemonic('e');
        menu_arquivo.setText("Files");
        menu_arquivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_quartos.setMnemonic('t');
        s_menu_quartos.setText("Quartos");
        s_menu_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_quartosActionPerformed(evt);
            }
        });
        menu_arquivo.add(s_menu_quartos);

        s_menu_produtos.setMnemonic('p');
        s_menu_produtos.setText("Produtos");
        s_menu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_produtosActionPerformed(evt);
            }
        });
        menu_arquivo.add(s_menu_produtos);

        menuBar.add(menu_arquivo);

        menu_reserva.setMnemonic('h');
        menu_reserva.setText("Reservations");
        menu_reserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_reservas.setMnemonic('c');
        s_menu_reservas.setText("Reservas e Consumos");
        menu_reserva.add(s_menu_reservas);

        s_menu_clientes.setMnemonic('a');
        s_menu_clientes.setText("Clientes");
        s_menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_clientesActionPerformed(evt);
            }
        });
        menu_reserva.add(s_menu_clientes);

        s_menu_pagamentos.setText("Pagamentos");
        menu_reserva.add(s_menu_pagamentos);

        menuBar.add(menu_reserva);

        menu_consulta.setText("Queries");
        menu_consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_consulta);

        menu_config.setText("Settings");
        menu_config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        s_menu_usuario.setText("Usuario e Acesso");
        s_menu_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_menu_usuarioActionPerformed(evt);
            }
        });
        menu_config.add(s_menu_usuario);

        menuBar.add(menu_config);

        menu_ferramenta.setText("System Tools");
        menu_ferramenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_ferramenta);

        menu_ajuda.setText("Help");
        menu_ajuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_ajuda);

        menu_sair.setText("Exit");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        menuBar.add(menu_sair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_menu_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_quartosActionPerformed
        FrmQuartos form = new FrmQuartos();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_quartosActionPerformed

    private void s_menu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_produtosActionPerformed
        FrmProdutos form = new FrmProdutos();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_produtosActionPerformed

    private void s_menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_clientesActionPerformed
        FrmClientes form = new FrmClientes();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_clientesActionPerformed

    private void s_menu_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_menu_usuarioActionPerformed
        FrmFuncionarios form = new FrmFuncionarios();
        menu.add(form);
        form.toFront();
        form.setVisible(true);
    }//GEN-LAST:event_s_menu_usuarioActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        this.dispose();
    }//GEN-LAST:event_menu_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane menu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menu_ajuda;
    private javax.swing.JMenu menu_arquivo;
    private javax.swing.JMenu menu_config;
    private javax.swing.JMenu menu_consulta;
    private javax.swing.JMenu menu_ferramenta;
    private javax.swing.JMenu menu_reserva;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_sistema;
    private javax.swing.JMenuItem s_menu_clientes;
    private javax.swing.JMenuItem s_menu_pagamentos;
    private javax.swing.JMenuItem s_menu_produtos;
    private javax.swing.JMenuItem s_menu_quartos;
    private javax.swing.JMenuItem s_menu_reservas;
    private javax.swing.JMenuItem s_menu_usuario;
    // End of variables declaration//GEN-END:variables

}
